# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mnenonen <mnenonen@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/27 17:02:52 by mnenonen          #+#    #+#              #
#    Updated: 2019/07/27 17:09:23 by mnenonen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=readrush

SOURCES=ft_bot.c ft_rush_collector.c ft_top.c ft_mid.c ft_strcpy.c\
	ft_read.c ft_strncpy.c ft_putstr.c

all:
	gcc $(SOURCES) -o $(NAME)

fclean:
	/bin/rm -f $(NAME)
